default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') { 'postgresql://user:password@localhost:5432' } %>

development:
  <<: *default
  database: support_tickets_development

test:
  <<: *default
  database: support_tickets_test

production:
  <<: *default
  database: support_tickets_production
